target-version = "py39"
line-length = 120

[lint]
select = ["E", "F", "W", "I", "N", "D", "UP", "S", "B", "A", "C4", "PT"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"tests/**" = ["S101", "D"]
